### ISSUE TITLE
Script errors and missing search params fields

### ISSUE THREAD

**Issue by petermicuch** [hapifhir/hapi-fhir-jpaserver-starter#181]
Start latest docker image based on 5.2.0
```
docker run -p 8080:8080 your_build_image
``` 
Load http://localhost:8080/ in browser and observe there are script errors (select2.css and select2.min.js gives 404). As a results you are not able to fill in search parameters., because there is only search parameter type, but you can not provide value.

I am not sure if starter has any effect here, or if this is only issue of base hapi project, because http://hapi.fhir.org/ does not show this error.

**Comment by vladonemo** [comment]
These resources come from select2 webjar. Not sure why the pom references version 4.0.3 of select2 webjar explicitly, but the structure of resources was different in that version and changed since version 4.0.3-1. 
I'd recommend to to remove the explicit version from pom and let the version come from the parent (hapi-fhir) pom instead.
This is actually the case for all the webjars, not just select2. After removing the version (so that the 4.0.13 is picked up from parent pom) I don't get 404 any longer.

**Comment by petermicuch** [comment]
@vladonemo thanks a lot for this catch. It indeed works fine as expected and I am able to enter values for search criteria now.

@jvitrifork , @jamesagnew  - is there specific reason to reference dedicated versions or could we take change from @vladonemo and even consider this change for other dependencies?

**Comment by jvitrifork** [comment]
the current version of select2 is new and came in the with the latest release of HAPI FHIR core 5.2.0, if I'm not mistaken. @jamesagnew this should be fixed in core, I believe.

**Comment by vladonemo** [comment]
@jvitrifork the 4.0.13 is new and the very same is referenced in the parent's HAPI FHIR core 5.2.0. But the starter references 4.0.3 (4 years old) version explicitly instead.

**Comment by jvitrifork** [comment]
oh ... thats unfortunate. @vladonemo, you're right. Parent pom version should be used instead. Will you do the PR?

**Comment by vladonemo** [comment]
#184 and #185 for all the others ;)

**Comment by jvitrifork** [comment]
@petermicuch - both PR's are now merged to master. Can you confirm that the issues are now gone?

**Comment by petermicuch** [comment]
@jvitrifork yes, issues are gone now.
