### ISSUE TITLE
Unable To Debug On Intellij

### ISSUE THREAD

**Issue by nrfribeiro** [hapifhir/hapi-fhir-jpaserver-starter#188]
Hi,
I'm trying to debug the jpaserver-starter on my Intellij but I'm getting this error:

> Error: Unable to initialize main class ca.uhn.fhir.jpa.starter.Application
> Caused by: java.lang.NoClassDefFoundError: javax/servlet/Servlet

If I change javax.servlet scope from provided to compile. and now spring boot starts but I'm getting the following error.

`org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at ca.uhn.fhir.jpa.starter.Application.main(Application.java:33)
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:205)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:177)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
	... 9 common frames omitted`

**Comment by jvitrifork** [comment]
![image](https://user-images.githubusercontent.com/46567685/101276851-2c2f4800-37b0-11eb-961c-6b46b7f53c88.png)
 and your are using the maven profile 'boot'?

**Comment by nrfribeiro** [comment]
Hi,
Yes. But I'm also new to Intellij and Java and probably doing something wrong.
After selecting the profile, I execute the following.
![image](https://user-images.githubusercontent.com/14877110/101279111-ebd3c800-37b7-11eb-824f-e15b245133fc.png)

**Comment by jkiddo** [comment]
The boot profile is a maven compile time profile, not a spring runtime profile

**Comment by nrfribeiro** [comment]
thanks for the clarification and pacience.
So, can you tell me how do I run maven in debug mode? I know this must be obvious, but I'm newbie on Intellij / java

**Comment by jvitrifork** [comment]
See https://www.jetbrains.com/help/idea/work-with-maven-profiles.html#declare_maven_profiles

**Comment by vladonemo** [comment]
@nrfribeiro just select the `boot` maven profile, reload maven, then select the `Application` run configuration (the Spring Boot one) and click `Debug` button (SHIFT+F9)

![image](https://user-images.githubusercontent.com/2752296/102340063-580fb200-3f96-11eb-8a64-ab8adf86cd52.png)

**Comment by atarpley** [comment]
I experienced the same issue.  I was using the boot profile as the other posts here were saying.  It looked like I was doing everything correctly.  But no dice.
I ended up deleting my `.idea/` folder and the `.iml` file and reimporting the project.  It worked like a charm after that.

**Comment by joeflack4** [comment]
I'm having the same problem. I'm a newbie with debugging Java web apps.

1. 
<img width="733" alt="Screen Shot 2022-04-03 at 7 00 41 PM" src="https://user-images.githubusercontent.com/13045020/161452542-a5666721-cbaf-4b72-a6f6-c2287004b202.png">

2. 
<img width="246" alt="Screen Shot 2022-04-03 at 7 00 57 PM" src="https://user-images.githubusercontent.com/13045020/161452543-0b97b0ce-36bf-431c-8385-3c1bd723db91.png">

3.
<img width="712" alt="Screen Shot 2022-04-03 at 7 01 06 PM" src="https://user-images.githubusercontent.com/13045020/161452544-8a7eb658-e2df-49bb-b46d-55f62b2c5cc1.png">

Step 3 doens't work for me. There is no Application config; there are no configs.

**Comment by joeflack4** [comment]
It looks like this was because I had the free, community edition installed. I just paid up and now have Ultimate.

Now I'm trying to debug as described above and in [the readme]([1.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/8405840/1.txt)
[2.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/8405841/2.txt)). But I get errors.

I'm working with two different clones; (1) is my server, which is basically a fork with almost no changes, and (2) is my colleague's, where he has made some changes.

## Server 1
I have no problem running this server in the command line with `docker-compose` or with `mvn -Djetty.port=8888 jetty:run`.

Debugger error full logs: 
[1.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/8405879/1.txt)

This is the only error I see:
```
2022-04-03 19:57:46.606 [http-nio-8080-exec-1] ERROR org.thymeleaf.TemplateEngine [TemplateEngine.java:1136] [THYMELEAF][http-nio-8080-exec-1] Exception processing template "home": An error happened during template parsing (template: "ServletContext resource [/WEB-INF/templates/home.html]")
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "ServletContext resource [/WEB-INF/templates/home.html]")
...
Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/templates/home.html]
```

I don't have `home.html` in my `WEB-INF/templates/` folder. But even on the current master branch of the main project, i'ts not there either:
<img width="953" alt="Screen Shot 2022-04-03 at 8 07 27 PM" src="https://user-images.githubusercontent.com/13045020/161455077-dcbbe9ca-7c9a-4aa8-9e22-e5a4c1565439.png">

Why is it searching for something that doesn't exist?
How can I fix this error and debug locally?

## Server 2
This is my colleague's server. I'm able to run it with `mvn -Djetty.port=8888 jetty:run`. But can't run via debugger either.

Debugger error full logs: [2.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/8405841/2.txt)

Error 1:
```
java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/templates/home.html]
```

This is the same error I'm seeing with "Server 1" above.

Error 2:
```
java.lang.NullPointerException: Cannot invoke "ca.uhn.fhir.context.support.ValueSetExpansionOptions.isFailOnMissingCodeSystem()" because "theExpansionOptions" is null
```

I know that this is a problem with some new code we've added to this project, and I think I can figure out how to fix this. But I'm curious as to why I can run the server normally without issue, but only get this error when running with the debugger.

**Comment by jkiddo** [comment]
1) You don't need a commercial license to IntelliJ for debugging the project
2) The UI does not load when you are running it as a debug instance from within Intellij. This is a known bug. All the rest of the FHIR server does run. Go to eg. /fhir/metadata when you are debugging - then you should see that all the REST endpoints are working perfectly fine.

**Comment by joeflack4** [comment]
Thanks @jkiddo . Maybe so, regarding to (1) maybe so, but I tried a bunch of different ways, both on stackoverflow and reading the HAPI docs, and for the life of me, I couldn't figure it out. Just so you know, the instructions that you have [in the readme](https://github.com/hapifhir/hapi-fhir-jpaserver-starter#running-hapi-fhir-jpaserver-directly-from-intellij-as-spring-boot) do _not_ work for the IntelliJ community edition. Regarding the spring boot method, you can look at my screenshots a few comments up above which show that the debug button does not appear when following those instructions. Regarding [tomcat](https://github.com/hapifhir/hapi-fhir-jpaserver-starter#running-hapi-fhir-jpaserver-directly-from-intellij-as-spring-boot), the "Application Servers" menu/option doesn't appear in the free community version.

Regarding (2), it seems you are correct! I closed my other issue.
