### ISSUE TITLE
jpa.properties always overridden 

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir-jpaserver-starter#199]
Changing jpa.properties in the application.yml has no effect as they are always overridden here:
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/4d3e76bf5178eac6e2838e90ec4e6ba50bf9e9cb/src/main/java/ca/uhn/fhir/jpa/starter/EnvironmentHelper.java#L21

`environment.getProperty("spring.jpa.properties")` always returns null, as getProperty doesn't support a search of partial properties.

Looking at this problem also made me thinking if it is a good idea to set default properties in code, couldn't the default settings being just included in the application.yml?

**Comment by jvitrifork** [comment]
The way it currently works is that either you supply **all** the values explicitly or you go with the default values.

**Comment by rbhman** [comment]
This is a bug as far as I'm concerned. Even if you have **all** the jpa properties present, it will **not** pick up your properties, since there exists no single property just called "spring.jpa.properties"

I just spent days trying to figure out why a certain jpa property was not being picked up from my yaml file, as I was attempting to handle multiple application profiles and deploying for the first time to a remote Tomcat server not using the default profile (running as e.g. -Dspring.profile.active=QA) I naturally assumed something was wrong with the multiple profiles, active profile not set correctly, HAPI's usage of the r4 profile etc. etc. and that that was somehow the root of my problem.

Here's what I did to fix the problem - I was going to report this bug and fix today and found this conversation thread, so posting my solution here. 

This solution still relies on the user providing all the jpa properties - I guess a better solution would be to merge override properties.

```
public class EnvironmentHelper {

  public static Properties getHibernateProperties(ConfigurableEnvironment environment) {
    Properties properties = new Properties();

    Map<String, Object> jpaProps = getPropertiesStartingWith(environment, "spring.jpa.properties");

//    if (environment.getProperty("spring.jpa.properties", String.class) == null) {
    if (jpaProps.isEmpty()) {
      properties.put("hibernate.search.model_mapping", "ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory");
      properties.put("hibernate.format_sql", "false");
      properties.put("hibernate.show_sql", "false");
      properties.put("hibernate.hbm2ddl.auto", "update");
      properties.put("hibernate.jdbc.batch_size", "20");
      properties.put("hibernate.cache.use_query_cache", "false");
      properties.put("hibernate.cache.use_second_level_cache", "false");
      properties.put("hibernate.cache.use_structured_entries", "false");
      properties.put("hibernate.cache.use_minimal_puts", "false");
      properties.put("hibernate.search.default.directory_provider", "filesystem");
      properties.put("hibernate.search.default.indexBase", "target/lucenefiles");
      properties.put("hibernate.search.lucene_version", "LUCENE_CURRENT");
    } else {
      for (Map.Entry<String, Object> entry : jpaProps.entrySet()) {
        String strippedKey = entry.getKey().replace("spring.jpa.properties.", "");
        properties.put(strippedKey, entry.getValue());
      }
    }
    return properties;
  }
...
```

**Comment by jvitrifork** [comment]
@patrick-werner @rbhman 

How about the following:

```
    Map<String, Object> jpaProps = getPropertiesStartingWith(environment, "spring.jpa.properties");

    properties.putIfAbsent("hibernate.search.model_mapping", "ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory");
    properties.putIfAbsent("hibernate.format_sql", "false");
    properties.putIfAbsent("hibernate.show_sql", "false");
    properties.putIfAbsent("hibernate.hbm2ddl.auto", "update");
    properties.putIfAbsent("hibernate.jdbc.batch_size", "20");
    properties.putIfAbsent("hibernate.cache.use_query_cache", "false");
    properties.putIfAbsent("hibernate.cache.use_second_level_cache", "false");
    properties.putIfAbsent("hibernate.cache.use_structured_entries", "false");
    properties.putIfAbsent("hibernate.cache.use_minimal_puts", "false");
    properties.putIfAbsent("hibernate.search.default.directory_provider", "filesystem");
    properties.putIfAbsent("hibernate.search.default.indexBase", "target/lucenefiles");
    properties.putIfAbsent("hibernate.search.lucene_version", "LUCENE_CURRENT");

    for (Map.Entry<String, Object> entry : jpaProps.entrySet()) {
      String strippedKey = entry.getKey().replace("spring.jpa.properties.", "");
      properties.put(strippedKey, entry.getValue().toString());
    }
```
That respects explicitly provided values and provides sane defaults.

**Comment by rbhman** [comment]
Looks good...

**Comment by jvitrifork** [comment]
Fixed
