### ISSUE TITLE
Resthook callback to https endpoint throws SunCertPathBuilderException exception

### ISSUE THREAD

**Issue by eye2web** [hapifhir/hapi-fhir-jpaserver-starter#378]
When HAPI Tries to call the https webhook on resource change the following exception is thrown.
I tested this with version v.5.6.0, v.5.7.0, and custom build from main. The behaviour is the same.
```
Failure handling subscription payload for subscription: Subscription/example-subscription
ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HAPI-0005: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I tried to override the setDefaultSSLSocketFactory to disable TLS checking. And tried the following JVM arguments without any succes.
```
JAVA_OPTS=-Dcom.sun.net.ssl.checkRevocation=false
CATALINA_OPTS=-Dcom.sun.net.ssl.checkRevocation=false
```

**Comment by lucatmedmij** [comment]
@eye2web Did you find a solution? I run into the same error.

**Comment by XcrigX** [comment]
@lucatmedmij  - this exception generally points to a problem with a TLS certificate. My guess would be your webhook is using a self-signed certificate that is not trusted by your Java Runtime.

**Comment by lucatmedmij** [comment]
@XcrigX - the certificate I am using is a valid Let's Encrypt certificate and not a self signed cert. The thing is that the intermediate Root Certifcate of Let's encrypt recently changed. There is since 9 september 2024 a new intermediate Root named X10 for Let's encrypt. Now hapi server docker image contains the root and intermediate root certifcate which were available at build time. I would be nice with a helm chart to have an init container to supply updated (intermediate) root certifcates.
