### ISSUE TITLE
Integration tests need their own DB properties

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir-jpaserver-starter#44]
Currently if you change the starter to Postgresql or any other non-embedded DB, the integration tests are failing.
It would nice to default the tests to something embedded, allowing people to use their non-embedded DB, but not failing the tests in their CI environment.

**Comment by seanmcilvenna** [comment]
The hapi.properties is setup right now with defaults so that the war file builds (and tests) successfully. You can override the hapi.properties location with -Dhapi.properties=<CUSTOM_LOCATION> that points to an environment-specific hapi.properties file with your postgresql configuration. This would allow you to build the war without any test errors, but still use your postgresql database in your deployment environment.

**Comment by data-viz** [comment]
Hello Sean - I'm trying to deploy with docker-compose. For the integration test to pass during build, and to switch to MySQL in the deployed container, do I need to edit line 23 in Dockerfile (CMD ["java","-Dhapi.properties=/hapi-config/hapi.properties","-jar","/usr/local/jetty/start.jar"]), and point to a new hapi.properties file with MySQL specific properties mentioned in readme?
Apologies, I am new to this, and trying to follow all the instructions.

**Comment by seanmcilvenna** [comment]
You should not need to do that... Theoretically, you should not need to modify *anything* in the Dockerfile/image. 

According to [this](https://docs.docker.com/compose/environment-variables/), in the docker compose file's service, you can specify environment variables like so:

```
services:
  hapi: 
    environment:
      - JAVA_OPTS=-Dhapi.properties=/hapi-config
```

**Comment by jkiddo** [comment]
@patrick-werner you still have this need?

**Comment by patrick-werner** [comment]
> @patrick-werner you still have this need?

Switched to docker with external properties, closing here.
