### ISSUE TITLE
Publish docker images to docker-hub /quay

### ISSUE THREAD

**Issue by lburgazzoli** [hapifhir/hapi-fhir-jpaserver-starter#68]
It would be very nice to have an "official" hapi-fhir-jpaserver-starter docker images published to docker hub or quay so people can easily try it or use it with testcontainers for integration tests

**Comment by jamesagnew** [comment]
I have no idea what's involved in this... but if anyone (you? :) ) wanted to help out the help would definitely be welcomed

**Comment by seanmcilvenna** [comment]
I have a Dockerfile that builds the whole image on the docker server... I've been contemplating incorporating it into the public repo. I could push a built image to docker-hub, as well. But, I image you want an official "hapi-fhir" account/repo on docker hub, @jamesagnew . Do you already have one or is that something you would like me to create for you?

**Comment by lburgazzoli** [comment]
Yes it would be nice to have an official hapi-fhir repository on docker-hub/quay. 
The process of publishing an image can easilly be automated with github actions or directly from dockerhub/quay

**Comment by jamesagnew** [comment]
@seanmcilvenna I just checked and both `hapi` and `hapifhir` are taken on docker hub... but i've created `hapiproject`. Lol.

If you have an account I can add you to the org.

**Comment by seanmcilvenna** [comment]
@jamesagnew I'm "seanmcilvenna" on docker hub. Thanks!

**Comment by jamesagnew** [comment]
done

**Comment by seanmcilvenna** [comment]
I've created a PR for the Dockerfile updates I was talking about: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/69

I've also built the 4.1 version of the app and pushed the docker images to docker-hub here: https://hub.docker.com/repository/docker/hapiproject/hapi

@jamesagnew one minor issue... I was going to setup an automated build/push in docker-bub, but I don't appear to be a collaborator/maintainer on this project anymore, so it's not showing up as an option for me to select this repository in the settings of the docker-hub repo. Here is a screenshot of what I have: 

![image](https://user-images.githubusercontent.com/5384694/70484611-418c6c00-1aa1-11ea-8228-5691e7049ac9.png)

If you can add me as a collaborator (again?) I can do this for you... Otherwise, would need you to set it up to automatically push updates. With that said, I'm not sure it's a very big deal. Changes to this repo happen fairly rarely, so it may be best to just do a manual build/push to update the docker image(s).

**Comment by jamesagnew** [comment]
@seanmcilvenna Hmm weird. I definitely didn't remove you, and I still see you as an owner:

<img width="1075" alt="Screen Shot 2019-12-10 at 10 09 03 AM" src="https://user-images.githubusercontent.com/3465117/70541518-29fec300-1b35-11ea-9aff-ff13c953d9dc.png">

**Comment by jamesagnew** [comment]
Oh, maybe the issue was the `hapifhir` GitHub org not being linked to the DockerHub `hapiproject` org. I've linked them.

**Comment by seanmcilvenna** [comment]
It appears to be fixed now. I kicked off a build and it automatically/successfully created the hapi:latest image based on the master branch.

**Comment by jamesagnew** [comment]
@seanmcilvenna Is there anything we need to do when we release a new version of this project?

**Comment by seanmcilvenna** [comment]
In the future, I believe GitHub tags are the key for releases... I've never used the dockerhub-github integration, though, so I'd need to play with it to know for sure. Right now, any time the repo changes it rebuilds the docker image and tags it with the "latest" tag. I would think that if you put a github tag on the repo, it would create a new build for that tag's commit and create a docker tag that matches the github tag. That's my suspicion, not positive, though.

**Comment by jamesagnew** [comment]
Ok cool- Let's wait until we tag the the next release and see what happens
automatically and what we need to do manually. :)

**Comment by BMartinos** [comment]
Hi all, Thanks for getting an official HAPI FHIR docker repo. This is great! Will be great to get the auto builds setup to make use of the github release tags. This means that whenever a new release is tagged on github it will automatically create a new tagged docker image. 

Below is an example setup for re-building the `latest` tag whenever a pushed is made into master branch, as well as a tagged image when a new tagged release is created in github. Might still require some tweaks for anything more fancy

![Screenshot from 2020-01-27 10-59-51](https://user-images.githubusercontent.com/7311421/73161858-2202de80-40f5-11ea-8954-840c846ae36f.png)

**Comment by ckmaresca** [comment]
I know this issue is closed, but rather than opening another one, I just wanted to comment on documentation about the docker instance.   The current writeup on Docker.io is really confusing as it just copies both the build instructions and some docker instructions.   Can someone clean up the docs so that it's clearer and cross-link the Git README so that people know where to find the docker image?   

I'm also saying this as I've tried to build both the Maven project & Docker image four times on 3 different systems and all the builds fail (which is another issue), so having a working, documented docker image is pretty critical...  Thanks!

**Comment by seanmcilvenna** [comment]
I'm happy to take a stab in the next couple weeks at coming up with some better docker docs. Please create a separate ticket for this, though, so that the request doesn't get lost. Thanks!

**Comment by ckmaresca** [comment]
Will do - thanks!
