### ISSUE TITLE
Not detecting Custom Operations.

### ISSUE THREAD

**Issue by botoxparty** [hapifhir/hapi-fhir-jpaserver-starter#760]
Hi,

I am trying to add custom operations to my server however i'm having some issues getting things up and running. I'm trying to copy what's in the test cases so i've created an operation:

(it's in /src/main/java/ca/uhn/fhir/jpa/starter/custom/pkg1/CustomOperationBean.java)

```
package ca.uhn.fhir.jpa.starter.custom.pkg1;

import ca.uhn.fhir.rest.annotation.Operation;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.apache.commons.io.IOUtils;
import org.springframework.stereotype.Component;

import java.io.IOException;

/**
 * Code taken from hapi documentation on how to implement an operation which handles its own request/response
 * <a href="https://hapifhir.io/hapi-fhir/docs/server_plain/rest_operations_operations.html#manually-handing-requestresponse">...</a>
 */

@Component
public class CustomOperationBean {

	private static final org.slf4j.Logger ourLog = org.slf4j.LoggerFactory.getLogger(CustomOperationBean.class);

	@Operation(name = "$springBeanOperation", manualResponse = true, manualRequest = true)
	public void springBeanOperation(HttpServletRequest theServletRequest, HttpServletResponse theServletResponse)
		throws IOException {
		String contentType = theServletRequest.getContentType();
		byte[] bytes = IOUtils.toByteArray(theServletRequest.getInputStream());

		ourLog.info("Received call with content type {} and {} bytes", contentType, bytes.length);

		theServletResponse.setContentType("text/plain");
		theServletResponse.getWriter().write("springBean");
		theServletResponse.getWriter().close();
	}
}
```

and I have added the following to my `application.yaml`

```
hapi:
  fhir:
    custom-bean-packages: ca.uhn.fhir.jpa.starter.custom.pkg1
    custom-provider-classes: ca.uhn.fhir.jpa.starter.custom.pkg1.CustomOperationBean
```

However I always get an error starting the server:

```
hapi-fhir-jpaserver-start  | Caused by: ca.uhn.fhir.context.ConfigurationException: Provider class was not found on classpath: ca.uhn.fhir.jpa.starter.custom.pkg1.CustomOperationBean
```

Am i implementing this correctly? I can't see what I would be missing based on the documentation, test case, and @dconlan 's change in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/654

**Comment by dconlan** [comment]
Hi @botoxparty,

  How are you trying to run the hapi server?

One thing to note, the package for your custom bean is under ca.uhn.fhir.jpa.starter, this means it would already be included in the bean packages and you would not need the custom-bean-packages property. The first thing I'd be trying is not using that package but something that does not start with ca.uhn.fhir.jpa.starter.

If I put your code into the source base and run mvn spring-boot:run it will serve the operation once the custom-provider-classes property is set.

Here are some possible scenarios:

### 1. Creating a fork of  hapi-fhir-jpaserver-starter
For this one you don't have to use the custom operation extention, just update StarterJpaConfig.restfulServer method to register your operation provider with the restful server. The problem with this option is you then need to keep your source base up with changes to hapi-fhir-jpaserver-starter.

### 2. Creating a custom stand-alone docker image
With this one you would have a project which builds your custom operations into their own jar and have a docker build file that uses hapiproject/hapi:latest as the base image. In this case you will need to use the 2 properties so your custom code is added, but you will need to make sure the extra code is added to the docker image. If you look at the docker file for this project you will see it ends with this line
```
ENTRYPOINT ["java", "--class-path", "/app/main.war", "-Dloader.path=main.war!/WEB-INF/classes/,main.war!/WEB-INF/,/app/extra-classes", "org.springframework.boot.loader.PropertiesLauncher"]
```
notice the /app/extra-classes being added to the loader path. This is to include the additional code into the classpath so it can be access. So you need to create a new docker file that copies your extra code into /app/extra-classes and then ends with a copy of the ENTRYPOINT line above. The complication with not building your extra classes along with the original code base is that any dependancies which are not included in the base image will also need to be included into the extra-classes directory. One way to get just the extra dependancies is to set all the hapi ones with a scope of "provided" and then add something like this:
```
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>process-resources</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeScope>runtime</includeScope>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```
This will add an extra task to copy any dependancies into the target/lib directory. Then in your docker file you copy those files plus the built jar into the extra-classes directory of the docker image. For this one you don't need to be as active to keep up with the main hapi-fhir-jpaserver-starter code base. You do need to watch out for dependancy moving on, but if you use a named version of the docker image instead of latest it will prevent these issues.


### 3. Adding a custom operation to a docker-compose using hapi-fhir-jpaserver-starter image. 
Probably the prefered method. Like the custom docker image version you will still need to get the custom operaiton class and its dependancies into the extra-classes directory,  but now you just add them as a volume in the docker compose.

```
services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi.application.yaml
        target: /app/config/application.yaml
      - source: hapi-extra-classes
        target: /app/extra-classes
```
with hapi.application.yaml being your custom yaml file with the custom-bean-packages and custom-provider-classes properties set and hapi-extra-classes a directory containing the custom operations and any dependancies. 


Hope this helps.

**Comment by botoxparty** [comment]
hey @dconlan!

I was using the first method, now i'm using the third which I would agree is the preferred method

I've published an example of how i'm doing it here, https://github.com/botoxparty/fhir-operation-example. The interceptors are working correctly, the logs being printed from my operation's constructers are showing in my logs, but the endpoints are not working.

I always get this kind of response:

```
{
	"resourceType": "OperationOutcome",
	"issue": [
		{
			"severity": "error",
			"code": "not-supported",
			"diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[$accept] with parameters [[]]"
		}
	]
}
```

Any ideas?

**Comment by dconlan** [comment]
Try using POST instead of GET

**Comment by botoxparty** [comment]
I get the same message regardless. Do you happen to have a known working
example I could test?

**Comment by dconlan** [comment]
https://github.com/dconlan/hapi-custom-operation-demo

**Comment by XcrigX** [comment]
@botoxparty  - in your application yaml you have _custom-operation-classes_:
https://github.com/botoxparty/fhir-operation-example/blob/main/hapi.application.yaml#L29

That's not a property that HAPI picks up, as far as I can tell. Should that be _custom-provider-classes_ ?

**Comment by dconlan** [comment]
https://github.com/dconlan/hapi-custom-operation-demo/blob/7be6bf423b1ddba05658c2ba98e0592bb8b6515a/hapi.application.yaml#L185

I thought I used custom-provider-classes

**Comment by botoxparty** [comment]
OMG @XcrigX 
🙃

Not even LLM's picked that up when i would feed in the docs and examples.
